### ISSUE TITLE
Question about GRNN, Regression problem

### ISSUE THREAD

**Issue by dizzer87** [itdxer/neupy#165]
Hello.
Is GRNN algorithm support multi-input, multi-output problem in regression?
Now I have database in 
Sample number : 225
Input : 10 * 225
Output : 407 * 225
And I adapted your code in my database, 
it shows 
"ValueError: Target value must be one dimensional array"

Furthermore, 
do you have any recommendation for these regression problem?

Thank you

**Comment by itdxer** [comment]
Hi,
The error message shows you that GRNN works only with single value outputs (or vectors in case if you have multiple input samples). The simples way to solve your problem is to use backpropagation approach. It's flexible enough to cover your needs. Check this tutorial http://neupy.com/2015/07/04/boston_house_prices_dataset.html. It shows solution for regression with single value output, but you can easily generalize it to multiple value outputs.
