### ISSUE TITLE
On how to implement a custom error function

### ISSUE THREAD

**Issue by ivan-marroquin** [itdxer/neupy#202]
Hi,

Following the documentation for a custom error function, I have the following code:

```python
def metric_error(expected, predicted):
    labels= [1, 2, 3]
    yexpected= preprocessing.label_binarize(expected, classes= labels)
    ypredicted= preprocessing.label_binarize(predicted, classes= labels)
    metric= 1. - metrics.roc_auc_score(yexpected, ypredicted, average= 'micro') 
    return metric

def train_network(parameters):
    n_step= np.round(parameters['step'],3)
    network_1 = algorithms.GradientDescent(
        [
            layers.Input(4),
            n_layer(n_hidden, bias= init.Constant(n_bias1), weight= init.HeNormal()),
            layers.Softmax(3, weight= init.HeNormal()),
        ],
        step= np.float(n_step),
        verbose= False,
        error= metric_error)

    network_1.architecture()
    network_1.train(xtrain_data, enc_ytrain_data, epochs=500)
    prediction= network_1.predict(xvalidation_data).argmax(axis= 1) + 1
    n_train_errors= network_1.errors.normalized()
    error= estimators.mse(yvalidation_data, prediction)
    
    return {'loss': error,
                'status': STATUS_OK}
```

I get this error: Singleton array array(algo:network/var:network-output, dtype=object) cannot be considered a valid collection.

It seems that the values for "expected" and "predicted" are not passed correctly.

Any suggestions?

Thanks,

Ivan

**Comment by itdxer** [comment]
Hi,
Input to the `metric_error` function are the Theano variables. Neupy triggers this function in order to compile computational graph in Theano and it happens before training starts (in `__init__`). If you want custom function then you have to apply valid Theano operations to the input. You can check how neupy functions work: https://github.com/itdxer/neupy/blob/master/neupy/algorithms/gd/errors.py. Unfortunately, functions won't work with theano variables.

Also, I don't think that ROC AUC would be a good function to optimize. For classification, you can use `categorical_crossentropy` or `categorical_hinge` (http://neupy.com/pages/cheatsheet.html#error-functions)

**Comment by ivan-marroquin** [comment]
thanks
