### ISSUE TITLE
CMAC Properties

### ISSUE THREAD

**Issue by SusmithaNagaboina** [itdxer/neupy#205]
@itdxer 
Hello sir!
I  want to build a CMAC neural network.But I am confused about the properties of CMAC  ie quantization size and associative units size.I have googled about this , but I could not find it.Can you please help me how to fix this units size.And also can you please explain how to set generalization ie mapping from input space to associative memory.Eagerly waiting for your answer.Thanks in advance.

**Comment by itdxer** [comment]
Hi,
You can learn more about CMAC from this chapter: http://q12.org/phd/thesis/chapter3.pdf

CMAC requires inputs to be integer and when you use real numbers for your input than quantization becomes more important, since it allows you to convert real number to a set of integers. 

```python
quantized_input = (input_data * quantization).astype(int)
```

You can play around with this example in order to train your intuition:
https://github.com/itdxer/neupy/blob/master/examples/memory/cmac_basic.py

You can try to change qunatization to values like 1, 10, 50, 100, 1000 and try to see how quality of the prediction changes.

Second parameters is `associative unit size`. It defines number of maps that map input to a target values. The larger number of associative units the more memory network requires, you will have to train it longer and in some cases you require more data. But quality of your prediction typicaly much better with larger number of associative units. As in the previous example try to use different values like 2, 10, 50, 100 and check how prediction quality changes after you changed the value

What value to chose for the CMAC parameters dependence on data that you use. 

I hope it will help

**Comment by SusmithaNagaboina** [comment]
Thank you for your valuable response.
