### ISSUE TITLE
It´s possible to apply cross_val_score() form sklearn to neupy NN that has an addon like Weigth Elimination?

### ISSUE THREAD

**Issue by mcvta** [itdxer/neupy#222]
I´m trying to apply cross_val_score() to the following algorithm (neupy 0.6.5 and numpy 1.15.1):

```
cgnet = algorithms.LevenbergMarquardt(
    connection=[
        layers.Input(XTrain.shape[1]),
        layers.Linear(6),
        layers.Linear(1)],
        mu_update_factor=2,
        mu=0.1,
        shuffle_data=True,
        verbose=True,
        decay_rate=0.1,
        addons=[algorithms.WeightElimination])

kfold = KFold(n_splits=5, shuffle=True, random_state=7)
scores=cross_val_score(cgnet, XTrainScaled,yTrainScaled,scoring='neg_mean_absolute_error',cv=kfold,verbose=10)
print scores
print("Accuracy: %0.2f (+/- %0.2f)" % (scores.mean(), scores.std() * 2))
```

,and this is the error message I get:
```
TypeError: Cannot create a consistent method resolution
order (MRO) for bases LevenbergMarquardtWeightElimination, WeightElimination
```

Without WeightElimination or any other addon, cross_val_score(), works fine...

**Comment by itdxer** [comment]
Thank you for reporting this issue. It also doesn't work in the new upcoming version as well (0.7.0) . Right now addons work in a bit over-complicated way. That's why the `clone` function has hard time copying this class. I'll probably need to change this interface in the future.

The other problem will be related to the weight re-initialization. I don't think that even without addons it works properly. Even if network get's copied, parameters probably get copied as well and network that you've trained for the next fold will do better than it should only because it has been pre-trained by the previous fold. It also means that data, that has been used during the training, in the next k-fold iteration will be used for validation and score won't give you proper reflection of the networks performance, because network has already seen these data samples in the previous fold.

At least, I should put these notes in the documentation to make sure that other users are aware of this issue: http://neupy.com/docs/algorithms/sklearn-compatibility.html

I'll also need to think about the permanent solution.

**Comment by itdxer** [comment]
You can, but you need to run cross validation loop explicitly, rather than using the `cross_val_score` function for it.

```
for train_data, test_data in kfold.split(data):
    network = init_model()
    prediction = make_prediction(network, test_data)
    score = score_prediction(prediction, test_data)
```
