### ISSUE TITLE
Tensorflow backend 

### ISSUE THREAD

**Issue by alfredaita** [itdxer/neupy#228]
Requirements states:  "TensorFlow from Anaconda.
On windows 10 .   Within anaconda3 python 37, had to create a py36 enviornment to install tensorflow with PIP not anaconda [only way I could get a clean install]. 
Can neupy be installed with tensorflow from pip?
Alfred

**Comment by itdxer** [comment]
Yes, but it's better to use tensorflow from anaconda. If you install tensorflow from pip it will be noticeably slower.

Also, I'm not sure how well tensorflow works in the python 3.7. Recently they had syntaxerror because of the used words like `async` in the code, but I believe it has been fixed already. In the official documentation they state that tensorflow "Requires Python 3.4, 3.5, or 3.6", see https://www.tensorflow.org/install/pip#1-install-the-python-development-environment-on-your-system

**Comment by alfredaita** [comment]
TF does not work with 3.7 oddly Theano does. I have not found there to be a performance deprecation using pip, but I have not checked it as thorough as should be.

**Comment by itdxer** [comment]
You can check this article, it compare tensorflow performance from pip and conda: https://towardsdatascience.com/stop-installing-tensorflow-using-pip-for-performance-sake-5854f9d9eb0c
